#Configuracion Local ( usando nuestro Docker y MySQL )

spring:
  datasource:
    url: ${DB_URL}
    username : ${DB_USERNAME}
    password : ${DB_PASSWORD}

  # Para activar hibernate DDL auto y forzar a spring a que use nuestro scrips
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


  sql:
    init:
      mode: never # va intercambiar entre never y always para cargar schemas.sql
      schema-locations: classpath:schema.sql


